apiVersion: v1
baseDomain: starksenterprise.com
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: starksenterprise.com
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: us-east-1
publish: External
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfMzFmYTNjODcwNDEyNDRlNjkzZjRiYjc3N2M3MWJkOWQ6NDBaQ09OWkFMNUVYTVMxMUsyM0tBQVVVRFFXQUVUNkJXR0RVTUxQRlVQWkY3S1hYRFBWOUM1M0FaTVpXNTVTUg==","email":"ncsu.ee2017@gmail.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfMzFmYTNjODcwNDEyNDRlNjkzZjRiYjc3N2M3MWJkOWQ6NDBaQ09OWkFMNUVYTVMxMUsyM0tBQVVVRFFXQUVUNkJXR0RVTUxQRlVQWkY3S1hYRFBWOUM1M0FaTVpXNTVTUg==","email":"ncsu.ee2017@gmail.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLTg0YThmZjIxLTllOTEtNGUzNC05OGZhLWRhYmQ1N2ZjYTBhOTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmtZak5pTURFd01qWmhNVFUwTlRkak9EQXdNekZoTTJRd05tWXhaREZsWmlKOS5paDdhOWNGcktFQXM3US1yRFZkSGF2REM0NlRSRVZsbGh5X1BTSjhkaXdOdEl1anY4QXZDbjlSbVZHSVVlR3R6T2NTSDVCb25XMUROZll6alJLd2NsWXdaX3dCVlozVW96OHFHeEZaaHNVdmt4SDVEcFRKUGx1OVo4c1B6amUyYWdVSVR4SjRHd0QyZGNOdXpDMnRsQWpVSjl1QlhjTmROZ1g5cUhwclgzdVBwb29yTEFtMU10NGhYVUZCWGpJZXFEb3ZBM01RcHdUeGxyUFVMNmtKOExxcFk4VDVPQWsxUXFEYWFGSmUtNXExa0IwY19hMWRYSVFTRDRxT3J2SFIybDlxU1VGQVdNbFZBaXFOUFgwa1dKNjFKdzdLSE9BMEFBWHQ4TXVhNGllN3JrQjJ3U3N6X1RneEhQWTRhSld2Y1ZMbjRpbTFFYzlBNm04ak5TeExQLXdsQ1puNVNzYjUyUWRtbFBfdGNYNWE3V0I1LUFyRUp5NzZRTldiODJMWUdMakJYSjdPai01V3BrdzQ3SGU2bmpiWnhWWTI2RDZPSkxjb3ZKalNzRUZyc2phRXJpX1VZZlg3T2Y4eWEwc1pzRkVHN0taalQyWVBXYU5jbDdjWl9qS2w0aXJhYTkwcl9CTGEzR2ZTUTdDR2RSaDBRdjFLa1J4Wjg2T2hOSWNGQVVxVWExT3dNbTJXcnllXzgwck5jdjZuUmN3WFRzb3lhRmhHaDRTN1BJU2EyaURSeGZseUx5b1Rjc1BWTGVNTGVTMlI1MUtRUHdkTXBkNzF5NEhnaGJ2QjZxV3RKRjJRYml4YlltU1ZRMWpkXzZmSTZGMXJJbzFtcTV3MTFvNnJNUEkwLUdpU3I2QkhrWnVFX0N2clJFMXpYcEQybmtOWUZmNVpjbldLTjVUSQ==","email":"ncsu.ee2017@gmail.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLTg0YThmZjIxLTllOTEtNGUzNC05OGZhLWRhYmQ1N2ZjYTBhOTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmtZak5pTURFd01qWmhNVFUwTlRkak9EQXdNekZoTTJRd05tWXhaREZsWmlKOS5paDdhOWNGcktFQXM3US1yRFZkSGF2REM0NlRSRVZsbGh5X1BTSjhkaXdOdEl1anY4QXZDbjlSbVZHSVVlR3R6T2NTSDVCb25XMUROZll6alJLd2NsWXdaX3dCVlozVW96OHFHeEZaaHNVdmt4SDVEcFRKUGx1OVo4c1B6amUyYWdVSVR4SjRHd0QyZGNOdXpDMnRsQWpVSjl1QlhjTmROZ1g5cUhwclgzdVBwb29yTEFtMU10NGhYVUZCWGpJZXFEb3ZBM01RcHdUeGxyUFVMNmtKOExxcFk4VDVPQWsxUXFEYWFGSmUtNXExa0IwY19hMWRYSVFTRDRxT3J2SFIybDlxU1VGQVdNbFZBaXFOUFgwa1dKNjFKdzdLSE9BMEFBWHQ4TXVhNGllN3JrQjJ3U3N6X1RneEhQWTRhSld2Y1ZMbjRpbTFFYzlBNm04ak5TeExQLXdsQ1puNVNzYjUyUWRtbFBfdGNYNWE3V0I1LUFyRUp5NzZRTldiODJMWUdMakJYSjdPai01V3BrdzQ3SGU2bmpiWnhWWTI2RDZPSkxjb3ZKalNzRUZyc2phRXJpX1VZZlg3T2Y4eWEwc1pzRkVHN0taalQyWVBXYU5jbDdjWl9qS2w0aXJhYTkwcl9CTGEzR2ZTUTdDR2RSaDBRdjFLa1J4Wjg2T2hOSWNGQVVxVWExT3dNbTJXcnllXzgwck5jdjZuUmN3WFRzb3lhRmhHaDRTN1BJU2EyaURSeGZseUx5b1Rjc1BWTGVNTGVTMlI1MUtRUHdkTXBkNzF5NEhnaGJ2QjZxV3RKRjJRYml4YlltU1ZRMWpkXzZmSTZGMXJJbzFtcTV3MTFvNnJNUEkwLUdpU3I2QkhrWnVFX0N2clJFMXpYcEQybmtOWUZmNVpjbldLTjVUSQ==","email":"ncsu.ee2017@gmail.com"}}}'
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC72O9i3IGNw2/D118N/z1FnZzX1/nLPbUAPGF2RK3QWCXB37NdFRR9WO9aQD+bWdV0WXZ+FBlVqWd1KL2+/5+HBVhjx5+8Ct0dqFdFVEiSAbWJ4X4VDIf9O94cx6wVSTDgh77GAoMEk/tu6ScK/1EhVEuyVPOFkcWq/bzA5NwGWqz3fX5QjZmUYiU/LY+CY1zrkp/AlsB3+wtwgJoktFhVp84glF5blG0usiwDsd7jZgrmyc5lACxUJ4RQwJtjiZWJMZgbbIVDlmClQBrO3WeG1jCensUULDcD34DbRIe4QIANWt0Y2p6UDBaCrIhcK05L3Le+1vMwfIny5L5EBYvIZF0sdpS2Urwa0SDxiZcotrGaws/+vyDez5mlV3Sw0x9qMS3RlER25/ZU+dbWjMlXRPbjxu5CN68HSXoutdnoOPDTekK6erJRp3aSF0lA7I6y9nm/NkHC9BLppsVh/59+pa21MzzVQeF+G8qwejZSIlSPVi3jELv672IRLEz7Vlc= irvs@Irvs-MacBook-Pro.local
